force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTradeController.cls
/**
 * @description       : 
 * @author            : Sudhir Kumar Thanna
 * @group             : 
 * @last modified on  : 04-12-2022
 * @last modified by  : Sudhir Kumar Thanna
**/
@IsTest
public with sharing class TestTradeController {

    @testSetup static void setup() {
        String buyAmount = '110';
        String buyCurrency = 'USD';
        String sellAmount = '100';
        String sellCurrency = 'EUR';
        String rate = '1.1';
        Trade__c tradeObj = new Trade__c();
        String genID = 'TR' + TradeController.generateRandomNum();
        tradeObj.Name = genID;
        tradeObj.ID__c = genID;
        tradeObj.Buy_Amount__c =  Decimal.valueOf(buyAmount).setScale(2, RoundingMode.HALF_UP);
        tradeObj.Buy_Currency__c = buyCurrency;
        tradeObj.Date_Booked__c = DateTime.now().format();
        tradeObj.Rate__c = Decimal.valueOf(rate);
        tradeObj.Sell_Amount__c = Decimal.valueOf(sellAmount).setScale(2, RoundingMode.HALF_UP);
        tradeObj.Sell_Currency__c = sellCurrency;
        insert tradeObj;
    }

    @IsTest
    public static void testCreateTrade() {
        String buyAmount = '110';
        String buyCurrency = 'USD';
        String sellAmount = '100';
        String sellCurrency = 'EUR';
        String rate = '1.1';
        Test.startTest();
        TradeController.createTrade(buyAmount, buyCurrency, sellAmount, sellCurrency, rate);
        List<Trade__c> tradeObj = TradeHelper.getTradeList();
        Test.stopTest();
        System.assert(tradeObj.size()>0 , 'Creation of Trade Object - Succesfull - Check Passed');
    }
}